name: build

on:
  workflow_dispatch:
  push:
    branches: [ '1.20.1' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: build
        run: |
          git clone https://github.com/North-Western-Development/oc2r.git
          cd oc2r
          mkdir libs
          wget https://github.com/perkinslr/oc2r/releases/latest/download/sedna.jar -O libs/sedna.jar
          git checkout 1.20.1
          ./gradlew build
