name: build

on:
  workflow_dispatch:
  push:
    branches: [ '1.20.1' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: build
        run: |
          git clone https://github.com/North-Western-Development/oc2r.git -b 1.20.1
          cd oc2r
          wget https://github.com/North-Western-Development/sedna-mc/releases/download/1.18.2-forge%2F1.0.46/sedna-1.18.2-forge-1.0.46+3176c2b.jar -O libs/sedna.jar
          ./gradlew build
