name: publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: build
        run: |
          git clone https://github.com/North-Western-Development/oc2r.git
          cd oc2r
          wget https://github.com/North-Western-Development/sedna-mc/releases/download/1.18.2-forge%2F1.0.44/sedna-1.18.2-forge-1.0.44+a24621e.jar -O libs/sedna.jar
          ./gradlew -Psemver='${{ github.event.release.tag_name }}' build

      - name: Update Manifest
        run: |
          cat oc2r/gradle.properties | grep semver >> $GITHUB_ENV

      - name: Create Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.semver }}
          allowUpdates: false
          draft: false
          prerelease: false
          token: ${{ github.token }}
          artifacts: "oc2r/build/libs/*.jar"
          tag: ${{ env.semver }}
