name: publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          wget https://github.com/North-Western-Development/sedna-mc/releases/download/1.18.2-forge%2F1.0.46/sedna-1.18.2-forge-1.0.46+3176c2b.jar -O libs/sedna.jar
          ./gradlew -Psemver='${{ github.event.release.tag_name }}' build

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/libs/*-all.jar"]'

      - name: Set release type to 'release'
        run: |
          echo "CURSEFORGE_RELEASE_TYPE=release" >> $GITHUB_ENV
        if: github.event.release.prerelease == false
      - name: Set release type to 'alpha'
        run: |
          echo "CURSEFORGE_RELEASE_TYPE=alpha" >> $GITHUB_ENV
        if: github.event.release.prerelease == true

      - name: Publish to Curseforge
        run: ./gradlew -Psemver='${{ steps.split_tag.outputs._1 }}' curseforge
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CURSEFORGE_RELEASE_TYPE: ${{ env.CURSEFORGE_RELEASE_TYPE }}
          CHANGELOG: ${{ github.event.release.body }}
